### PR TITLE
Build languages files

### PR DESCRIPTION
**Pull request by Jonic**
@tjvr Hey Tim (also @martinohanlon and @conoramurphy),

Your hunch was correct that if we setup a couple more options in rollup config I could get the languages files built and usable again. This PR introduces the work to do that, which includes two files that automatically call `scratchblocks.loadLanguages` with the translations they've defined.

With this change in place I can update our projects site and we should have everything we need, providing the `style` option in `renderMatching` doesn't change. Here's my plan:

* Get this approved and merged. I bumped the version to `3.1.3`, so we can tag and release it.
* Update the `scratchblocks.github.io` page to make the `3.1.3` files available as static assets I can remotely include on the projects site
* Update our projects site to use the `3.1.3` versions of the plugin

Once these are done, I'll be able to then update our tools that generate our projects content to allow authors to specify `scratch3` blocks.

How does all this sound? Hope it's all good with you :)

### CODE REVIEW

**Comment by tjvr** [comment]
There are some formatting changes in some of the JS files, are you able to revert these? (Or did they come from running `npm run fmt`, and I jusr forgot to last time? 🙈)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jonic** [comment]
I’m pretty sure the formatting changes were down to the `fmt` command, but will double check and revert if not.

So do you want this officially bumping to 4.0.0? Does that mean Scratch 3 support is now complete?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
I wouldn't say it's complete, but since this is an API change there should at least be a minor version bump I think? 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jonic** [comment]
Gotcha. 3.whatever.0 here we come! I’ll get that sorted tonight, and I do with double checking that the Node instructions in the README are still true, too!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
Looks good, feel free to merge! If you re-submit your PR against the home page, I can merge that too. Feel free to ping me by email if I miss the GitHub notification 🙂

Do you need me to publish to NPM, too?

**Comment by Jonic** [comment]
@tjvr Merged! An npm publish would be appreciated, yeah. I'll sort out a tagged release on this repo in the meantime. Ta for your help! I'll update my homepage PR too.

**Comment by Jonic** [comment]
@tjvr Second thoughts - I've tagged it, but I'll leave the release to you, because you know better than I do all the API changes that have gone into it! :)

**Pull request merged**
