### PR TITLE
Migrate scratch2, scratch3 to class syntax

### PR DESCRIPTION
**Pull request by tjvr**
This PR finishes migrating things from boring ol' `Object.prototype` to shiny new `class` syntax.  For #413.

### CODE REVIEW

**Comment by apple502j** [comment]
Seems like there is a regression (likely `CommentView#height`), fixing. (Snapshots test should've caught this, maybe we should run it without push...)

**Comment by apple502j** [comment]
Fixed the bug, but rendering of labels have changed?

**Comment by apple502j** [comment]
Nope, this PR did not cause that. Hmmm.

**Review by apple502j — APPROVED** [review]

**Comment by tjvr** [comment]
Thanks for spotting the CommentView mistake!

**Pull request merged**
